### ISSUE TITLE
custom label

### ISSUE THREAD

**Issue by lanceting** [TylerLH/react-native-timeago#13]
Hi Tyler,

Thanks for this.  

But i wanna know if there is a parameter where you can customize the labels... 
example: for seconds i want s only, minutes m, months mo.... so on... 

Cheers,
Lance

**Comment by TylerLH** [comment]
Since this component uses Moment.js under the hood, you should be able to use a custom locale with Moment directly. See http://momentjs.com/docs/#/customization/relative-time/ for more info.

**Comment by lanceting** [comment]
Thanks Tyler!
