### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by davide-scalzo** [TylerLH/react-native-timeago#2]
When the component is trying to refresh I get this warning:

Warning: forceUpdate(...): Can only update a mounted or mounting component. This usually means you called forceUpdate() on an unmounted component. This is a no-op. Please check the code for the undefined component.

Is there any way to fix this?

**Comment by TylerLH** [comment]
What's going on when this is happening? I can take a look but would be helpful to try and reproduce using your scenario. Thanks!

**Comment by davide-scalzo** [comment]
Sorry for the delay in replying to this.
Here's a screenshot of the error message.

![screen shot 2015-10-09 at 21 24 29](https://cloud.githubusercontent.com/assets/749029/10404702/3ffee352-6ecc-11e5-9b83-06bc0e9502b2.png)

I am simply calling it like this:
`<TimeAgo style={styles.date} time={review.createdAt.toISOString()} />`

**Comment by TylerLH** [comment]
It sounds as though PR #3 should take care of this issue. Try installing the latest version (0.1.0) from npm and let me know if there are any issues. Thanks @auser for the PR
